---
- hosts: localhost
  tasks:
  - name: Generate kube config on controllers
    ansible.builtin.command:
      cmd: "{{ item }}"
    with_items:
      - kubectl config set-cluster kubernetes-the-hard-way --certificate-authority=./crypto/ca.pem --embed-certs=true --server=https://10.240.0.21:6443 --kubeconfig=admin.kubeconfig
      - kubectl config set-credentials admin --client-certificate=./crypto/admin.pem --client-key=./crypto/admin-key.pem --embed-certs=true --kubeconfig=admin.kubeconfig
      - kubectl config set-context default --cluster=kubernetes-the-hard-way --user=admin --kubeconfig=admin.kubeconfig
      - kubectl config use-context default --kubeconfig=admin.kubeconfig
      - kubectl config use-context kubernetes-the-hard-way