---
- hosts: kubernetes
  gather_facts: yes
  become: yes

  vars_files:
    - vars/certs.yml

  vars:
    pod_cidr: 10.32.0.0/12

  tasks:
    #- import_tasks: plays/crypto.yml
    - name: add hosts to /etc/hosts
      lineinfile:
        line: "{{ item }}"
        path: /etc/hosts
      with_items:
        - 192.168.1.11     etcd-1.example.com       etcd-1
        - 192.168.1.12     etcd-2.example.com       etcd-2
        - 192.168.1.13     etcd-3.example.com       etcd-3
        - 192.168.1.21     controller-1.example.com controller-1
        - 192.168.1.22     controller-2.example.com controller-2
        - 192.168.1.31     worker-1.example.com     worker-1
        - 192.168.1.32     worker-2.example.com     worker-2
        - 192.168.1.200	lb.example.com		lb

    - import_tasks: tasks/etcd.yml
    - import_tasks: tasks/control.yml
    - import_tasks: tasks/worker.yml
