- name: Create required kubernetes directory
  file:
    state: directory
    path: "{{ item }}"
    mode: 755
  when: inventory_hostname in groups['controller']
  with_items:
    - /etc/kubernetes/config
    - /var/lib/kubernetes/

- name: Copy required certs/keys/token to /var/lib/kubernetes
  copy:
    src: "{{ item }}"
    dest: /var/lib/kubernetes/
    mode: 0400
  when:  inventory_hostname in groups['controller']
  with_items:
    - ./crypto/kubernetes-key.pem
    - ./crypto/kubernetes.pem
    - "{{ ca_path }}"
    - "{{ priv_key_path }}"
    - ./crypto/service-account-key.pem
    - ./crypto/service-account.pem
    - ./crypto/kube-scheduler-key.pem
    - ./crypto/kube-scheduler.pem
    - ./crypto/kube-proxy-key.pem
    - ./crypto/kube-proxy.pem
    - ./crypto/kube-controller-manager-key.pem
    - ./crypto/kube-controller-manager.pem
    - ./crypto/admin-key.pem
    - ./crypto/admin.pem
    - ./files/token.csv
    - ./crypto/encryption-config.yaml

- name:  Setup Kubernetes binaries
  get_url:
    url: "{{ item }}"
    dest: /usr/bin/
    mode: 0755
  when: inventory_hostname in groups['controller']
  with_items:
    - "https://storage.googleapis.com/kubernetes-release/release/v1.21.0/bin/linux/amd64/kube-apiserver"
    - "https://storage.googleapis.com/kubernetes-release/release/v1.21.0/bin/linux/amd64/kube-controller-manager"
    - "https://storage.googleapis.com/kubernetes-release/release/v1.21.0/bin/linux/amd64/kube-scheduler"
    - "https://storage.googleapis.com/kubernetes-release/release/v1.21.0/bin/linux/amd64/kubectl"

- name: create kube-apiserver.service from template
  template:
    src: templates/kube-apiserver.service.j2
    dest: /etc/systemd/system/kube-apiserver.service
  when: inventory_hostname in groups['controller']

- name: enable and start kube-apiserver service
  ansible.builtin.service:
    name: kube-apiserver
    state: started
    enabled: yes
  when: inventory_hostname in groups['controller']

- name: copy kube-controller-manager.service
  copy:
    src: files/kube-controller-manager.service
    dest: /etc/systemd/system/kube-controller-manager.service
  when: inventory_hostname in groups['controller']

- name: copy kube-scheduler.yaml
  copy:
    src: files/kube-scheduler.yaml
    dest: /etc/kubernetes/config/kube-scheduler.yaml
  when: inventory_hostname in groups['controller']

- name: Generate kube config on controllers
  ansible.builtin.command:
    cmd: "{{ item }}"
  with_items:
    # # kube-proxy config
    # - kubectl config set-cluster kubernetes-the-hard-way --certificate-authority=/var/lib/kubernetes/ca.pem --embed-certs=true --server=https://127.0.0.1:6443 --kubeconfig=/etc/kubernetes/config/kube-proxy.kubeconfig
    # - kubectl config set-credentials system:kube-proxy --client-certificate=/var/lib/kubernetes/kube-proxy.pem --client-key=/var/lib/kubernetes/kube-proxy-key.pem --embed-certs=true --kubeconfig=/etc/kubernetes/config/kube-proxy.kubeconfig
    # - kubectl config set-context default --cluster=kubernetes-the-hard-way --user=system:kube-proxy --kubeconfig=/etc/kubernetes/config/kube-proxy.kubeconfig
    # - kubectl config use-context default --kubeconfig=/etc/kubernetes/config/kube-proxy.kubeconfig
    # kube-controller-manager config
    - kubectl config set-cluster kubernetes-the-hard-way --certificate-authority=/var/lib/kubernetes/ca.pem --embed-certs=true --server=https://127.0.0.1:6443 --kubeconfig=/etc/kubernetes/config/kube-controller-manager.kubeconfig
    - kubectl config set-credentials system:kube-controller-manager --client-certificate=/var/lib/kubernetes/kube-controller-manager.pem --client-key=/var/lib/kubernetes/kube-controller-manager-key.pem --embed-certs=true --kubeconfig=/etc/kubernetes/config/kube-controller-manager.kubeconfig
    - kubectl config set-context default --cluster=kubernetes-the-hard-way --user=system:kube-controller-manager --kubeconfig=/etc/kubernetes/config/kube-controller-manager.kubeconfig
    - kubectl config use-context default --kubeconfig=/etc/kubernetes/config/kube-controller-manager.kubeconfig
    # kube-scheduler
    - kubectl config set-cluster kubernetes-the-hard-way --certificate-authority=/var/lib/kubernetes/ca.pem --embed-certs=true --server=https://127.0.0.1:6443 --kubeconfig=/etc/kubernetes/config/kube-scheduler.kubeconfig
    - kubectl config set-credentials system:kube-scheduler --client-certificate=/var/lib/kubernetes/kube-scheduler.pem --client-key=/var/lib/kubernetes/kube-scheduler-key.pem --embed-certs=true --kubeconfig=/etc/kubernetes/config/kube-scheduler.kubeconfig
    - kubectl config set-context default --cluster=kubernetes-the-hard-way --user=system:kube-scheduler --kubeconfig=/etc/kubernetes/config/kube-scheduler.kubeconfig
    - kubectl config use-context default --kubeconfig=/etc/kubernetes/config/kube-scheduler.kubeconfig
    # admin
    - kubectl config set-cluster kubernetes-the-hard-way --certificate-authority=/var/lib/kubernetes/ca.pem --embed-certs=true --server=https://127.0.0.1:6443 --kubeconfig=/etc/kubernetes/config/admin.kubeconfig
    - kubectl config set-credentials admin --client-certificate=/var/lib/kubernetes/admin.pem --client-key=/var/lib/kubernetes/admin-key.pem --embed-certs=true --kubeconfig=/etc/kubernetes/config/admin.kubeconfig
    - kubectl config set-context default --cluster=kubernetes-the-hard-way --user=admin --kubeconfig=/etc/kubernetes/config/admin.kubeconfig
    - kubectl config use-context default --kubeconfig=/etc/kubernetes/config/admin.kubeconfig
  when: inventory_hostname in groups['controller']

- name: enable and start kube-controller-manager service
  ansible.builtin.service:
    name: kube-controller-manager
    state: started
    enabled: yes
  when: inventory_hostname in groups['controller']

- name: copy kube-scheduler.service
  copy:
    src: files/kube-scheduler.service
    dest: /etc/systemd/system/kube-scheduler.service
  when: inventory_hostname in groups['controller']

- name: enable and start kube-controller-manager service
  ansible.builtin.service:
    name:  kube-scheduler
    state: started
    enabled: yes
  when: inventory_hostname in groups['controller']

- name: Add admin.kubeconfig to .bashrc
  ansible.builtin.lineinfile:
    line: "export KUBECONFIG=/etc/kubernetes/config/admin.kubeconfig"
    path: /root/.bashrc
  when: inventory_hostname in groups['controller']